version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - docker
      - dependencies

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - docker
      - dependencies

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - docker
      - gh-actions

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - docker
      - npm

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "main"
    labels:
      - docker
      - python
