version: "3.8"

services:
  db:
    image: nlpsandbox/mongo:0.1.0
    container_name: rocc-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - MONGO_USERNAME
      - MONGO_PASSWORD
    volumes:
      - database-data:/data/db
    ports:
      - "${MONGO_PORT}:27017"

  api:
    image: sagebionetworks/rocc:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: rocc-api
    environment:
      - SERVER_PROTOCOL
      - SERVER_DOMAIN
      - SERVER_PORT
      - DB_PROTOCOL
      - DB_DOMAIN=db
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - db

volumes:
  database-data:
