version: "3.8"

services:
  date-annotator:
    # image: nlpsandbox/date-annotator-example:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: rocc-server
    ports:
      - "8080:8080"