version: "3.8"

services:
  date-annotator:
    image: sagebionetworks/rocc-server:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: rocc-server
    ports:
      - "8080:8080"