# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
import re
from openapi_server import util

import re  # noqa: E501

class ChallengePlatformCreateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None):  # noqa: E501
        """ChallengePlatformCreateResponse - a model defined in OpenAPI

        :param id: The id of this ChallengePlatformCreateResponse.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'id': str
        }

        self.attribute_map = {
            'id': 'id'
        }

        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'ChallengePlatformCreateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ChallengePlatformCreateResponse of this ChallengePlatformCreateResponse.  # noqa: E501
        :rtype: ChallengePlatformCreateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this ChallengePlatformCreateResponse.

        The ID of the challenge platform  # noqa: E501

        :return: The id of this ChallengePlatformCreateResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChallengePlatformCreateResponse.

        The ID of the challenge platform  # noqa: E501

        :param id: The id of this ChallengePlatformCreateResponse.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501
        if id is not None and len(id) > 60:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `60`")  # noqa: E501
        if id is not None and len(id) < 1:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `1`")  # noqa: E501
        if id is not None and not re.search(r'^[a-z0-9]+(?:-[a-z0-9]+)*$', id):  # noqa: E501
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/^[a-z0-9]+(?:-[a-z0-9]+)*$/`")  # noqa: E501

        self._id = id
