# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DateRange(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, start_date=None, end_date=None):  # noqa: E501
        """DateRange - a model defined in OpenAPI

        :param start_date: The start_date of this DateRange.  # noqa: E501
        :type start_date: date
        :param end_date: The end_date of this DateRange.  # noqa: E501
        :type end_date: date
        """
        self.openapi_types = {
            'start_date': date,
            'end_date': date
        }

        self.attribute_map = {
            'start_date': 'startDate',
            'end_date': 'endDate'
        }

        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'DateRange':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DateRange of this DateRange.  # noqa: E501
        :rtype: DateRange
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_date(self):
        """Gets the start_date of this DateRange.

        Start date of the date range  # noqa: E501

        :return: The start_date of this DateRange.
        :rtype: date
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this DateRange.

        Start date of the date range  # noqa: E501

        :param start_date: The start_date of this DateRange.
        :type start_date: date
        """
        if start_date is None:
            raise ValueError("Invalid value for `start_date`, must not be `None`")  # noqa: E501

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this DateRange.

        End date of the date range  # noqa: E501

        :return: The end_date of this DateRange.
        :rtype: date
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this DateRange.

        End date of the date range  # noqa: E501

        :param end_date: The end_date of this DateRange.
        :type end_date: date
        """
        if end_date is None:
            raise ValueError("Invalid value for `end_date`, must not be `None`")  # noqa: E501

        self._end_date = end_date
