# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.tag import Tag
from openapi_server import util

from openapi_server.models.tag import Tag  # noqa: E501

class PageOfTagsAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tags=None):  # noqa: E501
        """PageOfTagsAllOf - a model defined in OpenAPI

        :param tags: The tags of this PageOfTagsAllOf.  # noqa: E501
        :type tags: List[Tag]
        """
        self.openapi_types = {
            'tags': List[Tag]
        }

        self.attribute_map = {
            'tags': 'tags'
        }

        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfTagsAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfTags_allOf of this PageOfTagsAllOf.  # noqa: E501
        :rtype: PageOfTagsAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tags(self):
        """Gets the tags of this PageOfTagsAllOf.

        An array of Tags  # noqa: E501

        :return: The tags of this PageOfTagsAllOf.
        :rtype: List[Tag]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this PageOfTagsAllOf.

        An array of Tags  # noqa: E501

        :param tags: The tags of this PageOfTagsAllOf.
        :type tags: List[Tag]
        """
        if tags is None:
            raise ValueError("Invalid value for `tags`, must not be `None`")  # noqa: E501

        self._tags = tags
