# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.challenge_organizer import ChallengeOrganizer
from openapi_server import util

from openapi_server.models.challenge_organizer import ChallengeOrganizer  # noqa: E501

class PageOfChallengeOrganizersAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, users=None):  # noqa: E501
        """PageOfChallengeOrganizersAllOf - a model defined in OpenAPI

        :param users: The users of this PageOfChallengeOrganizersAllOf.  # noqa: E501
        :type users: List[ChallengeOrganizer]
        """
        self.openapi_types = {
            'users': List[ChallengeOrganizer]
        }

        self.attribute_map = {
            'users': 'users'
        }

        self._users = users

    @classmethod
    def from_dict(cls, dikt) -> 'PageOfChallengeOrganizersAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PageOfChallengeOrganizers_allOf of this PageOfChallengeOrganizersAllOf.  # noqa: E501
        :rtype: PageOfChallengeOrganizersAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def users(self):
        """Gets the users of this PageOfChallengeOrganizersAllOf.

        An array of ChallengeOrganizers  # noqa: E501

        :return: The users of this PageOfChallengeOrganizersAllOf.
        :rtype: List[ChallengeOrganizer]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this PageOfChallengeOrganizersAllOf.

        An array of ChallengeOrganizers  # noqa: E501

        :param users: The users of this PageOfChallengeOrganizersAllOf.
        :type users: List[ChallengeOrganizer]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users
