# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PersonFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, first_name=None, last_name=None, email=None, organization=None):  # noqa: E501
        """PersonFilter - a model defined in OpenAPI

        :param first_name: The first_name of this PersonFilter.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this PersonFilter.  # noqa: E501
        :type last_name: str
        :param email: The email of this PersonFilter.  # noqa: E501
        :type email: str
        :param organization: The organization of this PersonFilter.  # noqa: E501
        :type organization: str
        """
        self.openapi_types = {
            'first_name': str,
            'last_name': str,
            'email': str,
            'organization': str
        }

        self.attribute_map = {
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'organization': 'organization'
        }

        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._organization = organization

    @classmethod
    def from_dict(cls, dikt) -> 'PersonFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersonFilter of this PersonFilter.  # noqa: E501
        :rtype: PersonFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def first_name(self):
        """Gets the first_name of this PersonFilter.

        Keep the persons whose first name starts with this term  # noqa: E501

        :return: The first_name of this PersonFilter.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this PersonFilter.

        Keep the persons whose first name starts with this term  # noqa: E501

        :param first_name: The first_name of this PersonFilter.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this PersonFilter.

        Keep the persons whose last name starts with this term  # noqa: E501

        :return: The last_name of this PersonFilter.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this PersonFilter.

        Keep the persons whose last name starts with this term  # noqa: E501

        :param last_name: The last_name of this PersonFilter.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this PersonFilter.

        Keep the persons whose email matches this term  # noqa: E501

        :return: The email of this PersonFilter.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PersonFilter.

        Keep the persons whose email matches this term  # noqa: E501

        :param email: The email of this PersonFilter.
        :type email: str
        """

        self._email = email

    @property
    def organization(self):
        """Gets the organization of this PersonFilter.

        Keep the persons who belong to this organization  # noqa: E501

        :return: The organization of this PersonFilter.
        :rtype: str
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this PersonFilter.

        Keep the persons who belong to this organization  # noqa: E501

        :param organization: The organization of this PersonFilter.
        :type organization: str
        """

        self._organization = organization
