# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.person_create_request import PersonCreateRequest
from openapi_server.models.person_create_response import PersonCreateResponse
from openapi_server import util

from openapi_server.models.person_create_request import PersonCreateRequest  # noqa: E501
from openapi_server.models.person_create_response import PersonCreateResponse  # noqa: E501

class Person(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, first_name=None, last_name=None, email=None, organization_ids=None):  # noqa: E501
        """Person - a model defined in OpenAPI

        :param id: The id of this Person.  # noqa: E501
        :type id: str
        :param first_name: The first_name of this Person.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Person.  # noqa: E501
        :type last_name: str
        :param email: The email of this Person.  # noqa: E501
        :type email: str
        :param organization_ids: The organization_ids of this Person.  # noqa: E501
        :type organization_ids: List[str]
        """
        self.openapi_types = {
            'id': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'organization_ids': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'organization_ids': 'organizationIds'
        }

        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._organization_ids = organization_ids

    @classmethod
    def from_dict(cls, dikt) -> 'Person':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Person of this Person.  # noqa: E501
        :rtype: Person
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Person.

        The ID of the person  # noqa: E501

        :return: The id of this Person.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Person.

        The ID of the person  # noqa: E501

        :param id: The id of this Person.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def first_name(self):
        """Gets the first_name of this Person.

        The first name of the person  # noqa: E501

        :return: The first_name of this Person.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this Person.

        The first name of the person  # noqa: E501

        :param first_name: The first_name of this Person.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this Person.

        The last name of the person  # noqa: E501

        :return: The last_name of this Person.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this Person.

        The last name of the person  # noqa: E501

        :param last_name: The last_name of this Person.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this Person.

        An email address  # noqa: E501

        :return: The email of this Person.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this Person.

        An email address  # noqa: E501

        :param email: The email of this Person.
        :type email: str
        """

        self._email = email

    @property
    def organization_ids(self):
        """Gets the organization_ids of this Person.

        The organizations the person belongs to  # noqa: E501

        :return: The organization_ids of this Person.
        :rtype: List[str]
        """
        return self._organization_ids

    @organization_ids.setter
    def organization_ids(self, organization_ids):
        """Sets the organization_ids of this Person.

        The organizations the person belongs to  # noqa: E501

        :param organization_ids: The organization_ids of this Person.
        :type organization_ids: List[str]
        """
        if organization_ids is None:
            raise ValueError("Invalid value for `organization_ids`, must not be `None`")  # noqa: E501

        self._organization_ids = organization_ids
