# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PersonCreateRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, email=None, organization_ids=None):  # noqa: E501
        """PersonCreateRequest - a model defined in OpenAPI

        :param name: The name of this PersonCreateRequest.  # noqa: E501
        :type name: str
        :param email: The email of this PersonCreateRequest.  # noqa: E501
        :type email: str
        :param organization_ids: The organization_ids of this PersonCreateRequest.  # noqa: E501
        :type organization_ids: List[str]
        """
        self.openapi_types = {
            'name': str,
            'email': str,
            'organization_ids': List[str]
        }

        self.attribute_map = {
            'name': 'name',
            'email': 'email',
            'organization_ids': 'organizationIds'
        }

        self._name = name
        self._email = email
        self._organization_ids = organization_ids

    @classmethod
    def from_dict(cls, dikt) -> 'PersonCreateRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersonCreateRequest of this PersonCreateRequest.  # noqa: E501
        :rtype: PersonCreateRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this PersonCreateRequest.


        :return: The name of this PersonCreateRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PersonCreateRequest.


        :param name: The name of this PersonCreateRequest.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def email(self):
        """Gets the email of this PersonCreateRequest.

        An email address  # noqa: E501

        :return: The email of this PersonCreateRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this PersonCreateRequest.

        An email address  # noqa: E501

        :param email: The email of this PersonCreateRequest.
        :type email: str
        """

        self._email = email

    @property
    def organization_ids(self):
        """Gets the organization_ids of this PersonCreateRequest.


        :return: The organization_ids of this PersonCreateRequest.
        :rtype: List[str]
        """
        return self._organization_ids

    @organization_ids.setter
    def organization_ids(self, organization_ids):
        """Sets the organization_ids of this PersonCreateRequest.


        :param organization_ids: The organization_ids of this PersonCreateRequest.
        :type organization_ids: List[str]
        """
        if organization_ids is None:
            raise ValueError("Invalid value for `organization_ids`, must not be `None`")  # noqa: E501

        self._organization_ids = organization_ids
