# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class PersonCreateResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, person_id=None):  # noqa: E501
        """PersonCreateResponse - a model defined in OpenAPI

        :param person_id: The person_id of this PersonCreateResponse.  # noqa: E501
        :type person_id: str
        """
        self.openapi_types = {
            'person_id': str
        }

        self.attribute_map = {
            'person_id': 'personId'
        }

        self._person_id = person_id

    @classmethod
    def from_dict(cls, dikt) -> 'PersonCreateResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersonCreateResponse of this PersonCreateResponse.  # noqa: E501
        :rtype: PersonCreateResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def person_id(self):
        """Gets the person_id of this PersonCreateResponse.

        The ID of the person  # noqa: E501

        :return: The person_id of this PersonCreateResponse.
        :rtype: str
        """
        return self._person_id

    @person_id.setter
    def person_id(self, person_id):
        """Sets the person_id of this PersonCreateResponse.

        The ID of the person  # noqa: E501

        :param person_id: The person_id of this PersonCreateResponse.
        :type person_id: str
        """

        self._person_id = person_id
