# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TagFilter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tag_id=None):  # noqa: E501
        """TagFilter - a model defined in OpenAPI

        :param tag_id: The tag_id of this TagFilter.  # noqa: E501
        :type tag_id: str
        """
        self.openapi_types = {
            'tag_id': str
        }

        self.attribute_map = {
            'tag_id': 'tagId'
        }

        self._tag_id = tag_id

    @classmethod
    def from_dict(cls, dikt) -> 'TagFilter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TagFilter of this TagFilter.  # noqa: E501
        :rtype: TagFilter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tag_id(self):
        """Gets the tag_id of this TagFilter.

        Keep the tags whose tagId starts with this term  # noqa: E501

        :return: The tag_id of this TagFilter.
        :rtype: str
        """
        return self._tag_id

    @tag_id.setter
    def tag_id(self, tag_id):
        """Sets the tag_id of this TagFilter.

        Keep the tags whose tagId starts with this term  # noqa: E501

        :param tag_id: The tag_id of this TagFilter.
        :type tag_id: str
        """

        self._tag_id = tag_id
