# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class TokenResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, token=None, expires_in=None):  # noqa: E501
        """TokenResponse - a model defined in OpenAPI

        :param token: The token of this TokenResponse.  # noqa: E501
        :type token: str
        :param expires_in: The expires_in of this TokenResponse.  # noqa: E501
        :type expires_in: datetime
        """
        self.openapi_types = {
            'token': str,
            'expires_in': datetime
        }

        self.attribute_map = {
            'token': 'token',
            'expires_in': 'expiresIn'
        }

        self._token = token
        self._expires_in = expires_in

    @classmethod
    def from_dict(cls, dikt) -> 'TokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TokenResponse of this TokenResponse.  # noqa: E501
        :rtype: TokenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def token(self):
        """Gets the token of this TokenResponse.


        :return: The token of this TokenResponse.
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this TokenResponse.


        :param token: The token of this TokenResponse.
        :type token: str
        """

        self._token = token

    @property
    def expires_in(self):
        """Gets the expires_in of this TokenResponse.


        :return: The expires_in of this TokenResponse.
        :rtype: datetime
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in):
        """Sets the expires_in of this TokenResponse.


        :param expires_in: The expires_in of this TokenResponse.
        :type expires_in: datetime
        """

        self._expires_in = expires_in
