# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.user_create_request import UserCreateRequest
from openapi_server.models.user_create_response import UserCreateResponse
import re
from openapi_server import util

from openapi_server.models.user_create_request import UserCreateRequest  # noqa: E501
from openapi_server.models.user_create_response import UserCreateResponse  # noqa: E501
import re  # noqa: E501

class User(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, role='user', first_name=None, last_name=None, email=None, organization_ids=None):  # noqa: E501
        """User - a model defined in OpenAPI

        :param username: The username of this User.  # noqa: E501
        :type username: str
        :param role: The role of this User.  # noqa: E501
        :type role: str
        :param first_name: The first_name of this User.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this User.  # noqa: E501
        :type last_name: str
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param organization_ids: The organization_ids of this User.  # noqa: E501
        :type organization_ids: List[str]
        """
        self.openapi_types = {
            'username': str,
            'role': str,
            'first_name': str,
            'last_name': str,
            'email': str,
            'organization_ids': List[str]
        }

        self.attribute_map = {
            'username': 'username',
            'role': 'role',
            'first_name': 'firstName',
            'last_name': 'lastName',
            'email': 'email',
            'organization_ids': 'organizationIds'
        }

        self._username = username
        self._role = role
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._organization_ids = organization_ids

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this User.

        The username of the user  # noqa: E501

        :return: The username of this User.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this User.

        The username of the user  # noqa: E501

        :param username: The username of this User.
        :type username: str
        """
        if username is not None and len(username) > 25:
            raise ValueError("Invalid value for `username`, length must be less than or equal to `25`")  # noqa: E501
        if username is not None and len(username) < 3:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `3`")  # noqa: E501
        if username is not None and not re.search(r'^[a-z0-9]+(?:-[a-z0-9]+)*$', username):  # noqa: E501
            raise ValueError("Invalid value for `username`, must be a follow pattern or equal to `/^[a-z0-9]+(?:-[a-z0-9]+)*$/`")  # noqa: E501

        self._username = username

    @property
    def role(self):
        """Gets the role of this User.

        The role of the user  # noqa: E501

        :return: The role of this User.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this User.

        The role of the user  # noqa: E501

        :param role: The role of this User.
        :type role: str
        """
        allowed_values = ["user", "admin"]  # noqa: E501
        if role not in allowed_values:
            raise ValueError(
                "Invalid value for `role` ({0}), must be one of {1}"
                .format(role, allowed_values)
            )

        self._role = role

    @property
    def first_name(self):
        """Gets the first_name of this User.

        The first name of the person  # noqa: E501

        :return: The first_name of this User.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this User.

        The first name of the person  # noqa: E501

        :param first_name: The first_name of this User.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this User.

        The last name of the person  # noqa: E501

        :return: The last_name of this User.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this User.

        The last name of the person  # noqa: E501

        :param last_name: The last_name of this User.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def email(self):
        """Gets the email of this User.

        An email address  # noqa: E501

        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.

        An email address  # noqa: E501

        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def organization_ids(self):
        """Gets the organization_ids of this User.

        The organizations the person belongs to  # noqa: E501

        :return: The organization_ids of this User.
        :rtype: List[str]
        """
        return self._organization_ids

    @organization_ids.setter
    def organization_ids(self, organization_ids):
        """Sets the organization_ids of this User.

        The organizations the person belongs to  # noqa: E501

        :param organization_ids: The organization_ids of this User.
        :type organization_ids: List[str]
        """
        if organization_ids is None:
            raise ValueError("Invalid value for `organization_ids`, must not be `None`")  # noqa: E501

        self._organization_ids = organization_ids
